name: CI

on: [push, pull_request]

jobs:
  roave_bc_check:
    name: Roave BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
        continue-on-error: true
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
        dependencies: ['lowest', 'highest']
    name: 'Psalm'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
      - name: Install Dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --no-progress
      - name: Install Dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer install --no-progress
      - name: Psalm
        run: vendor/bin/psalm --shepherd
  cs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
    name: 'CS'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-
      - name: Install Dependencies
        run: composer install --no-progress
      - name: CS
        run: vendor/bin/php-cs-fixer fix --diff --dry-run --diff-format udiff
